kind: pipeline
name: galactae-server

steps:
- name: pingone
  image: docker:git
  commands:
    ## this will show you if ``sonarqube`` is resolved.
    - ping -c 1 sonarqube
  when:
    branch:
    - master

- name: pingtwo
  image: docker:git
  ## Alas this will also be needed, and is NOT supported yet
  networks:
   - internal
  commands:
    ## this will show you if ``sonarqube`` is resolved.
    - ping -c 1 sonarqube
  when:
    branch:
    - master

- name: sonarqube
  image: aosapps/drone-sonar-plugin
  networks:
    - internal
  settings:
    sonar_host: ***REMOVED***/
    sonar_token: ***REMOVED***
    level: TRACE
    showProfiling: true
  when:
    branch:
    - master

- name: discord
  pull: default
  image: appleboy/drone-discord
  settings:
    webhook_id: ***REMOVED***
    webhook_token: ***REMOVED***
    message: >
      {{#success build.status}}
        Build on **PHP Custom Framework** on branch **{{build.branch}}** ({{truncate build.commit 8}}) succeeded.
      {{else}}
        Build on **PHP Custom Framework** on branch **{{build.branch}}** ({{truncate build.commit 8}}) failed.
      {{/success}}
  when:
    branch:
    - master
    event:
    - push
    status: 
    - changed
    - failure
    - success